from mininet.topo import Topo

class MyTopo( Topo ):
 
    def __init__( self ):
 
        Topo.__init__( self )
    

        host1 = self.addHost( 'h1' )
        host2 = self.addHost( 'h2' )
        host3 = self.addHost( 'h3' )
        host4 = self.addHost( 'h4' )
        host5 = self.addHost( 'h5' )
        host6 = self.addHost( 'h6' )
        host7 = self.addHost( 'h7' )
        host8 = self.addHost( 'h8' )
        host9 = self.addHost( 'h9' )
        host10 = self.addHost( 'h10' )
        host11 = self.addHost( 'h11' )
        host12 = self.addHost( 'h12' )
        host13 = self.addHost( 'h13' )
        host14 = self.addHost( 'h14' )
        host15 = self.addHost( 'h15' )
        host16 = self.addHost( 'h16' )
        host17 = self.addHost( 'h17' )
        host18 = self.addHost( 'h18' )
        host19 = self.addHost( 'h19' )
        host20 = self.addHost( 'h20' )
        host21 = self.addHost( 'h21' )
        host22 = self.addHost( 'h22' )
        host23 = self.addHost( 'h23' )
        host24 = self.addHost( 'h24' )
        host25 = self.addHost( 'h25' )
        host26 = self.addHost( 'h26' )
        host27 = self.addHost( 'h27' )
        host28 = self.addHost( 'h28' )
        host29 = self.addHost( 'h29' )
        host30 = self.addHost( 'h30' )
        host31 = self.addHost( 'h31' )
        host32 = self.addHost( 'h32' )
        host33 = self.addHost( 'h33' )
        host34 = self.addHost( 'h34' )
        host35 = self.addHost( 'h35' )
        host36 = self.addHost( 'h36' )
        host37 = self.addHost( 'h37' )
        host38 = self.addHost( 'h38' )
        host39 = self.addHost( 'h39' )
        host40 = self.addHost( 'h40' )
        host41 = self.addHost( 'h41' )
        host42 = self.addHost( 'h42' )
        host43 = self.addHost( 'h43' )
        host44 = self.addHost( 'h44' )
        host45 = self.addHost( 'h45' )
        host46 = self.addHost( 'h46' )
        host47 = self.addHost( 'h47' )
        host48 = self.addHost( 'h48' )
        host49 = self.addHost( 'h49' )
        host50 = self.addHost( 'h50' )
        host51 = self.addHost( 'h51' )
        host52 = self.addHost( 'h52' )
        host53 = self.addHost( 'h53' )
        host54 = self.addHost( 'h54' )
        host55 = self.addHost( 'h55' )
        host56 = self.addHost( 'h56' )
        host57 = self.addHost( 'h57' )
        host58 = self.addHost( 'h58' )
        host59 = self.addHost( 'h59' )
        host60 = self.addHost( 'h60' )
        host61 = self.addHost( 'h61' )
        host62 = self.addHost( 'h62' )
        host63 = self.addHost( 'h63' )
        host64 = self.addHost( 'h64' )
        host65 = self.addHost( 'h65' )
        host66 = self.addHost( 'h66' )
        host67 = self.addHost( 'h67' )
        host68 = self.addHost( 'h68' )
        host69 = self.addHost( 'h69' )
        host70 = self.addHost( 'h70' )
        host71 = self.addHost( 'h71' )
        host72 = self.addHost( 'h72' )
        host73 = self.addHost( 'h73' )
        host74 = self.addHost( 'h74' )
        host75 = self.addHost( 'h75' )
        host76 = self.addHost( 'h76' )
        host77 = self.addHost( 'h77' )
        host78 = self.addHost( 'h78' )
        host79 = self.addHost( 'h79' )
        host80 = self.addHost( 'h80' )
        host81 = self.addHost( 'h81' )
        host82 = self.addHost( 'h82' )
        host83 = self.addHost( 'h83' )
        host84 = self.addHost( 'h84' )
        host85 = self.addHost( 'h85' )
        host86 = self.addHost( 'h86' )
        host87 = self.addHost( 'h87' )
        host88 = self.addHost( 'h88' )
        host89 = self.addHost( 'h89' )
        host90 = self.addHost( 'h90' )
        host91 = self.addHost( 'h91' )
        host92 = self.addHost( 'h92' )
        host93 = self.addHost( 'h93' )
        host94 = self.addHost( 'h94' )
        host95 = self.addHost( 'h95' )
        host96 = self.addHost( 'h96' )
        host97 = self.addHost( 'h97' )
        host98 = self.addHost( 'h98' )
        host99 = self.addHost( 'h99' )
        host100 = self.addHost( 'h100' )

        switch1 = self.addSwitch( 's1' )
        switch2 = self.addSwitch( 's2' )
        switch3 = self.addSwitch( 's3' )
        switch4 = self.addSwitch( 's4' )
        switch5 = self.addSwitch( 's5' )
        
        self.addLink( host1, switch1 )
        self.addLink( host2, switch1 )
        self.addLink( host3, switch1 )
        self.addLink( host4, switch1 )
        self.addLink( host5, switch1 )
        self.addLink( host6, switch1 )
        self.addLink( host7, switch1 )
        self.addLink( host8, switch1 )
        self.addLink( host9, switch1 )
        self.addLink( host10, switch1 )
        self.addLink( host11, switch1 )
        self.addLink( host12, switch1 )
        self.addLink( host13, switch1 )
        self.addLink( host14, switch1 )
        self.addLink( host15, switch1 )
        self.addLink( host16, switch1 )
        self.addLink( host17, switch1 )
        self.addLink( host18, switch1 )
        self.addLink( host19, switch1 )
        self.addLink( host20, switch1 )
        self.addLink( host21, switch2 )
        self.addLink( host22, switch2 )
        self.addLink( host23, switch2 )
        self.addLink( host24, switch2 )
        self.addLink( host25, switch2 )
        self.addLink( host26, switch2 )
        self.addLink( host27, switch2 )
        self.addLink( host28, switch2 )
        self.addLink( host29, switch2 )
        self.addLink( host30, switch2 )
        self.addLink( host31, switch2 )
        self.addLink( host32, switch2 )
        self.addLink( host33, switch2 )
        self.addLink( host34, switch2 )
        self.addLink( host35, switch2 )
        self.addLink( host36, switch2 )
        self.addLink( host37, switch2 )
        self.addLink( host38, switch2 )
        self.addLink( host39, switch2 )
        self.addLink( host40, switch2 )
        self.addLink( host41, switch3 )
        self.addLink( host42, switch3 )
        self.addLink( host43, switch3 )
        self.addLink( host44, switch3 )
        self.addLink( host45, switch3 )
        self.addLink( host46, switch3 )
        self.addLink( host47, switch3 )
        self.addLink( host48, switch3 )
        self.addLink( host49, switch3 )
        self.addLink( host50, switch3 )
        self.addLink( host51, switch3 )
        self.addLink( host52, switch3 )
        self.addLink( host53, switch3 )
        self.addLink( host54, switch3 )
        self.addLink( host55, switch3 )
        self.addLink( host56, switch3 )
        self.addLink( host57, switch3 )
        self.addLink( host58, switch3 )
        self.addLink( host59, switch3 )
        self.addLink( host60, switch3 )
        self.addLink( host61, switch4 )
        self.addLink( host62, switch4 )
        self.addLink( host63, switch4 )
        self.addLink( host64, switch4 )
        self.addLink( host65, switch4 )
        self.addLink( host66, switch4 )
        self.addLink( host67, switch4 )
        self.addLink( host68, switch4 )
        self.addLink( host69, switch4 )
        self.addLink( host70, switch4 )
        self.addLink( host71, switch4 )
        self.addLink( host72, switch4 )
        self.addLink( host73, switch4 )
        self.addLink( host74, switch4 )
        self.addLink( host75, switch4 )
        self.addLink( host76, switch4 )
        self.addLink( host77, switch4 )
        self.addLink( host78, switch4 )
        self.addLink( host79, switch4 )
        self.addLink( host80, switch4 )
        self.addLink( host81, switch5 )
        self.addLink( host82, switch5 )
        self.addLink( host83, switch5 )
        self.addLink( host84, switch5 )
        self.addLink( host85, switch5 )
        self.addLink( host86, switch5 )
        self.addLink( host87, switch5 )
        self.addLink( host88, switch5 )
        self.addLink( host89, switch5 )
        self.addLink( host90, switch5 )
        self.addLink( host91, switch5 )
        self.addLink( host92, switch5 )
        self.addLink( host93, switch5 )
        self.addLink( host94, switch5 )
        self.addLink( host95, switch5 )
        self.addLink( host96, switch5 )
        self.addLink( host97, switch5 )
        self.addLink( host98, switch5 )
        self.addLink( host99, switch5 )
        self.addLink( host100, switch5 )
        self.addLink( switch1, switch2 )
        self.addLink( switch1, switch3 )
        self.addLink( switch2, switch3 )
        self.addLink( switch2, switch4 )
        self.addLink( switch3, switch5 )
        self.addLink( switch4, switch5 )
        
topos = { 'mytopo': ( lambda: MyTopo() ) }
